### ISSUE TITLE
GAX replayer/tracker checklist

### ISSUE THREAD

**Issue by beanieaxolotl** [beanieaxolotl/shinen-gax-python#11]
I have gotten most of the stuff done on this. Right now there is a replayer engine that aims to closely mimic GAX's functionality, and an editor/tracker for the .gax files. These are the current standing issues that are still present in the programs (more specifically the replayer):

- [x] Figure out accurate pitch slide calculation (Most noticeable in Sigma Star Saga)
- [x] Implement tone portamento
- [x] Figure out accurate tone portamento calculation (Most noticeable in The SpongeBob SquarePants Movie, SpongeBob Lights Camera Pants, etc.)
- [x] Fix bug in which tone portamento cannot go downwards
- [x] Figure out note pitch tuning problems (this affects Drake & Josh, Unfabulous, etc.)
- [x] Implement note delay
- [x] Implement vibrato
- [x] Figure out vibrato depth calculation problems (it's slightly imperfect)
- [x] Fix the volume envelope sustain bug
- [x] Fix a few packing/unpacking bugs

**Comment by beanieaxolotl** [comment]
Recently just implemented note delay. It is a bit of a hack (at least for me), because it has the channel object's ticking rely on not only the replayer, but the GAX object's instrument set as well, and I usually like things more self-contained, but it seems to mostly work so far (there are a few edge cases regarding Rayman Raving Rabbids, though). The change is not pushed just yet however.

![image](https://github.com/user-attachments/assets/ed01008f-8fc9-4506-bde1-8e751ac15f03)
